# Generated by Django 3.1.4 on 2020-12-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_verification',
        ),
        migrations.AddField(
            model_name='user',
            name='user_verification_back',
            field=models.ImageField(null=True, upload_to='', verbose_name='本人確認（裏）'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_verification_front',
            field=models.ImageField(null=True, upload_to='', verbose_name='本人確認（表）'),
        ),
    ]
