# Generated by Django 3.1.4 on 2020-12-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20201222_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_verification_back',
            field=models.ImageField(null=True, upload_to='', verbose_name='本人確認（裏）'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_verification_front',
            field=models.ImageField(null=True, upload_to='', verbose_name='本人確認（表）'),
        ),
    ]
