# Generated by Django 3.1.4 on 2020-12-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_auto_20201222_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twitter_key',
            field=models.IntegerField(null=True, verbose_name='アクセスキー'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_secret',
            field=models.IntegerField(null=True, verbose_name='アクセスシークレットキー'),
        ),
    ]
