# Generated by Django 3.1.4 on 2020-12-25 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_auto_20201225_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='twitter_key',
            new_name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter_secret',
        ),
    ]
