# Generated by Django 3.1.4 on 2020-12-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_auto_20201225_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='twitter_url',
            field=models.CharField(max_length=255, null=True, verbose_name='ツイッターのURL'),
        ),
    ]
