# Generated by Django 3.1.4 on 2020-12-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_auto_20201225_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='geted',
            field=models.BooleanField(default=False, verbose_name='認証住み'),
        ),
    ]
