# Generated by Django 3.1.4 on 2021-01-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_user_geted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
    ]
