# Generated by Django 3.1.4 on 2021-01-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_auto_20210103_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_account_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_city_kana',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_city_kanji',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_day',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_first_name_kana',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_first_name_kanji',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_holder_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_last_name_kana',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_last_name_kanji',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_line1_kana',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_line1_kanji',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_line2_kana',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_line2_kanji',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_month',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_postal_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_routing_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_state_kana',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_state_kanji',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_tos_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_town_kana',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_town_kanji',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_verification_back',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_verification_front',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_year',
        ),
    ]
