# Generated by Django 3.1.4 on 2021-01-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0012_auto_20210104_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='describe1',
            field=models.TextField(default='・値段/n\n・コースの内容\n    （対戦してフィードバックする、リプレイを送ってもらってフィードバックする、\n    質問をする権利を○日まで与える。。。などコース内容は自由に決めても良いですが、\n    永久コンサル、戦闘力〇〇まで上げる等はトラブルの元になりやすいのでなるべくお控えください。）\n・コースを終える基準（〜日まで、○回戦するまで、○本のリプレイを送ってもらうまで、等。\n    明確な終了条件を設けるようにお願いします。）\n    ', verbose_name='コース1の説明'),
        ),
        migrations.AlterField(
            model_name='user',
            name='describe2',
            field=models.TextField(default='・値段/n\n・コースの内容\n    （対戦してフィードバックする、リプレイを送ってもらってフィードバックする、\n    質問をする権利を○日まで与える。。。などコース内容は自由に決めても良いですが、\n    永久コンサル、戦闘力〇〇まで上げる等はトラブルの元になりやすいのでなるべくお控えください。）\n・コースを終える基準（〜日まで、○回戦するまで、○本のリプレイを送ってもらうまで、等。\n    明確な終了条件を設けるようにお願いします。）\n    ', verbose_name='コース2の説明'),
        ),
        migrations.AlterField(
            model_name='user',
            name='describe3',
            field=models.TextField(default='・値段/n\n・コースの内容\n    （対戦してフィードバックする、リプレイを送ってもらってフィードバックする、\n    質問をする権利を○日まで与える。。。などコース内容は自由に決めても良いですが、\n    永久コンサル、戦闘力〇〇まで上げる等はトラブルの元になりやすいのでなるべくお控えください。）\n・コースを終える基準（〜日まで、○回戦するまで、○本のリプレイを送ってもらうまで、等。\n    明確な終了条件を設けるようにお願いします。）\n    ', verbose_name='コース3の説明'),
        ),
    ]
