# Generated by Django 3.1.4 on 2021-01-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0022_auto_20210106_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='menter',
            field=models.IntegerField(choices=[(1, 'メンター'), (2, 'メンティー')], default=0, verbose_name='会員形式'),
        ),
    ]
