# Generated by Django 3.1.4 on 2021-01-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0024_auto_20210108_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False, verbose_name='既読'),
        ),
    ]
