# Generated by Django 3.1.4 on 2021-01-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0025_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notice',
            field=models.BooleanField(default='False', verbose_name='やりとりしている人たち'),
        ),
    ]
